name: "publish vscode extension"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: yarn install:all
      - run: yarn build:webview
      - run: npm install -g @vscode/vsce
      - name: publish
        run: yarn deploy
        env:
          VSCE_USER: ${{secrets.VSCE_USER}}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
